security:
    password_hashers:
        App\Entity\Users:
            algorithm: auto

    providers:
        users_in_memory: { memory: null } # ou ton provider basé sur Users si tu utilises la BDD
        app_users_provider:
            entity:
                class: App\Entity\Users
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|assets)/
            security: false

        main:
            lazy: true
            provider: app_users_provider
            custom_authenticator: App\Security\UsersAuthenticator
            entry_point: App\Security\UsersAuthenticator # <--- Important !
            logout:
                path: app_logout
                target: app_login
    access_control:
        - { path: ^/admin, roles: ROLE_GESTIONNAIRE }